### ISSUE TITLE
When I highlight and type ", the variable disappear

### ISSUE THREAD

**Issue by shinokada** [jeff-hykin/better-shell-syntax#10]
Before installing Better shell syntax, I could highlight a variable and type " to wrap the variable with ".

But after installation, when I do it, the variable disappear,s and only " is typed.

```
mydir=$(dirname $0)

# becomes
mydir=$(dirname ")

# I expect this
mydir=$(dirname "$0")
```

**Comment by jeff-hykin** [comment]
Hmm, for me this still works. 

<img width="265" alt="Screen Shot 2021-02-12 at 5 05 59 PM" src="https://user-images.githubusercontent.com/17692058/107831888-b2d64780-6d54-11eb-9932-7a6b7b881b84.png">
Then I press the `"` key and I get
<img width="294" alt="Screen Shot 2021-02-12 at 5 06 35 PM" src="https://user-images.githubusercontent.com/17692058/107831908-c1246380-6d54-11eb-96dc-57651af411bb.png">

**Comment by jeff-hykin** [comment]
(just let me know and I'll open this issue back up)
