### ISSUE TITLE
Dash options split over several lines are parsed as commands

### ISSUE THREAD

**Issue by AbysmalBiscuit** [jeff-hykin/better-shell-syntax#11]
The grammar for dash options fails to capture options that are passed over several lines using a `\`.
Options are instead captured as commands.

For example, the following `-DWITH_SOMEFLAG=ON` will be captured as a `constant.other.option.shell`:
```bash
cmake ../project -DWITH_SOMEFLAG=ON
make
```

Whereas the following `-DWITH_SOMEFLAG=ON` will be captured as a `entity.name.command.shell`:
```bash
cmake ../project \
  -DWITH_SOMEFLAG=ON
make
```

As far as I am aware, no shell uses commands prefixed with a dash.
There is also a convention of not naming scripts with one or more leading dashes, as dashes are used for flags/options.

Hence, it would make sense to capture things prefixed with a `-` that are split over several lines using a `\` as either one or both of the following:
- constant.other.option.dash.shell
- constant.other.option.shell

**Comment by jeff-hykin** [comment]
should now be fixed on `v1.2.5`
