### ISSUE TITLE
Regression: Latest version breaks highlighting from nested quotes inside braces after semi-colon on same line in sh mode.

### ISSUE THREAD

**Issue by MarximusMaximus** [jeff-hykin/better-shell-syntax#29]
VSCode Version: 1.74.1
better-shell-syntax version: 1.2.9
OS: macOS 12.6

Previously was working. Seems to be when there is a command separated by a semi-colon on the same line as a function definition with cuddled braces and a quoted parameter expansion with quotes inside.

Example Code:
```sh
#!/usr/bin/env sh

# works:
a="${-:+"-$-"}"

# works:
date() {
    a="${-:+"-$-"}"
    set +x; if [ -n "${a}" ]; then set -x; else set +x; fi

    if [ "$(uname)" = "Darwin" ]; then
        command date -j "$@"
    else
        command date "$@"
    fi

    set +x ${a}
    unset a
}

# works:
nulldef; date()
{
    a="${-:+"-$-"}"
    set +x; if [ -n "${a}" ]; then set -x; else set +x; fi

    if [ "$(uname)" = "Darwin" ]; then
        command date -j "$@"
    else
        command date "$@"
    fi

    set +x ${a}
    unset a
}

# does not work:
nulldef; date() {
    a="${-:+"-$-"}"
    set +x; if [ -n "${a}" ]; then set -x; else set +x; fi

    if [ "$(uname)" = "Darwin" ]; then
        command date -j "$@"
    else
        command date "$@"
    fi

    set +x ${a}
    unset a
}
```

Results:
![Screen Shot 2022-12-15 at 18 19 12](https://user-images.githubusercontent.com/94208961/208007070-d65de3ea-4aa7-4bfd-b3b1-db45882eb22f.png)

Expected similar to:
![Screen Shot 2022-12-15 at 18 19 24](https://user-images.githubusercontent.com/94208961/208007083-44d63eea-7ae6-472f-babc-4c1ef290d392.png)

**Comment by jeff-hykin** [comment]
Should be fixed now with `v1.3.0`
