### ISSUE TITLE
Advanced parameter expansion can cause brackets to be miscolored on multiple lines

### ISSUE THREAD

**Issue by andreicaba** [jeff-hykin/better-shell-syntax#30]
Hello

Congrats for your work, first of all :) Good job!
Here's a bug:
after a certain character sequence, it stops factoring in the characters that remain to the right of the sequence.
Example:
```sh
declare s a=(a b c)
{
    s=${a[-${#a[@]}]}
}
```
![image](https://user-images.githubusercontent.com/45318272/212285013-056bf980-7a3a-4a5f-9f18-3baf1d9cc7c0.png)

The last two characters "]}" seemed to not have been factored in - as the first opening "{" bracket has a different colour than the closing "}" bracket.

**Comment by jeff-hykin** [comment]
While there is a problem, I think bracket pair colorization is making the problem a lot worse. The outer pair of `{}` do seem to be tagged correctly, but, as you mention, the `]}` is the source of the problem, where the bracket pair colorization gets confused.

I'll actually upgrade this issue to a much larger issue, which is that the syntax doesn't really support anything beyond the most basic form of [parameter expansion](https://wiki.bash-hackers.org/syntax/pe) 


supported
- `$PARAMETER`
- `${PARAMETER}`
not really supported:
- Indirection
  - `${!PARAMETER}`
- Case modification
  - `${PARAMETER^}`
  - `${PARAMETER^^}`
  - `${PARAMETER,}`
  - `${PARAMETER,,}`
  - `${PARAMETER~}`
  - `${PARAMETER~~}`
- Variable name expansion
  - `${!PREFIX*}`
  - `${!PREFIX@}`
- Substring removal (also for filename manipulation!)
  - `${PARAMETER#PATTERN}`
  - `${PARAMETER##PATTERN}`
  - `${PARAMETER%PATTERN}`
  - `${PARAMETER%%PATTERN}`
- Search and replace
  - `${PARAMETER/PATTERN/STRING}`
  - `${PARAMETER//PATTERN/STRING}`
  - `${PARAMETER/PATTERN}`
  - `${PARAMETER//PATTERN}`
- String length
  - `${#PARAMETER}`
- Substring expansion
  - `${PARAMETER:OFFSET}`
  - `${PARAMETER:OFFSET:LENGTH}`
- Use a default value
  - `${PARAMETER:-WORD}`
  - `${PARAMETER-WORD}`
- Assign a default value
  - `${PARAMETER:=WORD}`
  - `${PARAMETER=WORD}`
- Use an alternate value
  - `${PARAMETER:+WORD}`
  - `${PARAMETER+WORD}`
- Display error if null or unset
  - `${PARAMETER:?WORD}`
  - `${PARAMETER?WORD}`

**Comment by jeff-hykin** [comment]
As of v1.8.5 the bracket issue should be fixed. I'll use a new issue to track general parameter expansion
