### ISSUE TITLE
Syntax highlighting issue with curly brace in string

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-shell-syntax#32]
If you remove the `{` from `"${args[@]}"` the issue resolves. 

```shell
#!/bin/bash
function run_args() {
	args=("date" "--utc")
	"${args[@]}"
	echo 'use "quota" here'
}
run_args
```

![image](https://user-images.githubusercontent.com/10379994/216523720-afd6b85b-6ed6-4159-9fde-dd6b2502a10d.png)

Originally from @ladyrick in https://github.com/microsoft/vscode/issues/173246

**Comment by jeff-hykin** [comment]
should be fixed with `v1.3.1`
