### ISSUE TITLE
switch case not being highlighted properly

### ISSUE THREAD

**Issue by shadichy** [jeff-hykin/better-shell-syntax#33]
![image](https://user-images.githubusercontent.com/60534636/216610326-e45c0e7f-4866-448c-a64c-fc5cab5d06bf.png)
why is the ")" red?

**Comment by jeff-hykin** [comment]
That will depend on your theme as to why. The `)` has a tag of "punctuation.definition.case-pattern" and your theme picks the color for that tag

**Comment by jeff-hykin** [comment]
As far as I can tell the syntax is highlighting the correct thing, but if you think there's still a problem let me know and I'll open the issue back up

**Comment by shadichy** [comment]
> punctuation.definition.case-pattern

within this extension disabled, 
![image](https://user-images.githubusercontent.com/60534636/216752242-2a95c140-cf4f-44a4-8c43-1a9056a3de90.png)
it's white

**Comment by shadichy** [comment]
also, this doen't highlight variables inside {} like this
![image](https://user-images.githubusercontent.com/60534636/216752315-82ee1aa6-4c3e-4994-8f70-ec0c23739b35.png)
while the default theme does

**Comment by jeff-hykin** [comment]
> > punctuation.definition.case-pattern
> 
> within this extension disabled, ![image](https://user-images.githubusercontent.com/60534636/216752242-2a95c140-cf4f-44a4-8c43-1a9056a3de90.png) it's white

The built-in VS Code syntax is an older version that doesn't match everything. So your theme doesn't know the ) is punctuation, and just colors it white.

**Comment by jeff-hykin** [comment]
> also, this doen't highlight variables inside {} like this ![image](https://user-images.githubusercontent.com/60534636/216752315-82ee1aa6-4c3e-4994-8f70-ec0c23739b35.png) while the default theme does

Here's what it looks like for me with the Material theme:

<img width="434" alt="Screen Shot 2023-02-04 at 3 06 00 PM" src="https://user-images.githubusercontent.com/17692058/216789594-6c7ba1c3-b287-400a-a654-bdfcbab84dff.png">

If you want to customize/tweak the colors of your current theme, take a look a tutorial here:

https://jeffhykin.medium.com/how-to-customize-your-vs-code-text-colors-c0191155f41a

**Comment by shadichy** [comment]
> > > punctuation.definition.case-pattern
> > 
> > 
> > within this extension disabled, ![image](https://user-images.githubusercontent.com/60534636/216752242-2a95c140-cf4f-44a4-8c43-1a9056a3de90.png) it's white
> 
> The built-in VS Code syntax is an older version that I believe doesn't match/tag everything. So your theme probably doesn't know the `)` is punctuation, and just colors it white.

switched to material, also set
![image](https://user-images.githubusercontent.com/60534636/216796578-749373ce-6307-4f3e-a244-50be3d43ba99.png)
still
![image](https://user-images.githubusercontent.com/60534636/216796586-fc1705b4-2bef-45c6-b46e-5269813def1a.png)

**Comment by jeff-hykin** [comment]
Ohhh now I actually think it's the bracket-pair-colorizer being confused. It thinks those )'s are part of a pair. There should be a setting for disabling bracket pair colorizing, and it can be done on a language specific basis.


It became obvious because I don't think that shade of red is even part of the material theme color pallet.

**Comment by 0xjc** [comment]
@jeff-hykin I noticed this issue as well. The `unbalancedBracketScopes` addition seems related: https://github.com/microsoft/vscode/issues/144736

The [default shellscript extension](https://github.com/microsoft/vscode/blob/main/extensions/shellscript/package.json) has this:

```
    "grammars": [
      {
        "language": "shellscript",
        "scopeName": "source.shell",
        "path": "./syntaxes/shell-unix-bash.tmLanguage.json",
        "balancedBracketScopes": [
          "*"
        ],
        "unbalancedBracketScopes": [
          "meta.scope.case-pattern.shell"
        ]
      }
    ],
```

**Comment by frypf** [comment]
Was there ever any fix for this? I've just installed this extension (to get around buggy highlighting introduced by VSC 1.76.0), and it only seems to be an issue while it's enabled.

**Comment by shadichy** [comment]
> Was there ever any fix for this? I've just installed this extension (to get around buggy highlighting introduced by VSC 1.76.0), and it only seems to be an issue while it's enabled.

same case here
no idea when it will be fixed

**Comment by jeff-hykin** [comment]
> @jeff-hykin I noticed this issue as well. The `unbalancedBracketScopes` addition seems related: [microsoft/vscode#144736](https://github.com/microsoft/vscode/issues/144736)
> 
> The [default shellscript extension](https://github.com/microsoft/vscode/blob/main/extensions/shellscript/package.json) has this:
> 
> ```
>     "grammars": [
>       {
>         "language": "shellscript",
>         "scopeName": "source.shell",
>         "path": "./syntaxes/shell-unix-bash.tmLanguage.json",
>         "balancedBracketScopes": [
>           "*"
>         ],
>         "unbalancedBracketScopes": [
>           "meta.scope.case-pattern.shell"
>         ]
>       }
>     ],
> ```

Alright, I've added something similar to see if that fixes the bracket pair issue
