### ISSUE TITLE
Multiline arrays indented with tabs break syntax highlighting

### ISSUE THREAD

**Issue by misaki-web** [jeff-hykin/better-shell-syntax#35]
## The code with a problem is:

```bash
#!/bin/bash

echo "Start"

array_not_ok=(
	"Lorem ipsum"
	"dolor sit"
	"amet"
)

echo "End"
```

## It looks like this (theme "Default Light+") when indented with tabs:

![screenshot-bash-highlighting-bug-array](https://user-images.githubusercontent.com/64830812/216805663-5b926f22-7192-4550-bca0-71edf2c3766c.png)

## It should look like this (indented with spaces):

![screenshot-bash-highlighting-bug-array-2](https://user-images.githubusercontent.com/64830812/216805739-689d891f-1fb6-450c-a27b-114664a8073c.png)

**Comment by jeff-hykin** [comment]
should be fixed now with `v1.3.3`
