### ISSUE TITLE
Arrays preceded by an indented empty line break highlighting

### ISSUE THREAD

**Issue by misaki-web** [jeff-hykin/better-shell-syntax#36]
## The code with a problem is:

```bash
#!/bin/bash

echo "start"

if [[ $TEST_ENV1 == "10 - 1" ]]; then
	echo "inside if"
	
	test_array=("Lorem ipsum" "dolor sit" "amet")
fi

echo "end"
```

## It looks like this (theme "Default Light+"):

![screenshot-bash-highlighting-bug-array-loop](https://user-images.githubusercontent.com/64830812/216806430-798a3546-fac0-4110-a98a-8a3f926869b0.png)

## It should look like this:

There's no issue if the empty line is not indented:

![screenshot-bash-highlighting-bug-array-loop-2](https://user-images.githubusercontent.com/64830812/216806564-1eac84bf-c274-4996-9fbd-3748caf7c90f.png)

**Comment by jeff-hykin** [comment]
this should also be fixed now with `v1.3.3`
