### ISSUE TITLE
Unquoted plus function syntax breaks highlighting

### ISSUE THREAD

**Issue by mattmc3** [jeff-hykin/better-shell-syntax#38]
## The code with a problem is:

If using the `(( ! ${+functions[foo]} ))` syntax, highlighting breaks.

https://github.com/ohmyzsh/ohmyzsh/blob/87f1941d27df2e9a3390e5d1cddf6c264ba7311d/plugins/magic-enter/magic-enter.plugin.zsh#L19-L38

## It looks like:

All the red...

<img width="701" alt="Screenshot 2023-02-07 at 10 19 20 AM" src="https://user-images.githubusercontent.com/978625/217286082-79efbd85-e349-43ca-b0a7-ebbbd599e049.png">

## It should look like:

Remove the `+` to see without the red...

<img width="700" alt="Screenshot 2023-02-07 at 10 19 31 AM" src="https://user-images.githubusercontent.com/978625/217286053-8199221f-d0a1-4816-9360-7571c369997a.png">

**Comment by mattmc3** [comment]
Just to clarify - I'm using the latest version (v1.3.5), which I installed as an extension from https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-shellscript-syntax&ssr=false#review-details since the version shipped with this month's VS Code was broken in other ways.

**Comment by mattmc3** [comment]
Sorry, looks like this went away when I closed and reloaded VSCode, which may mean that the extension with the latest version wasn't properly loaded. Since I can no longer reproduce, I'm closing this issue. Sorry to trouble you.

**Comment by jeff-hykin** [comment]
I'm both surprised this was a problem in the first and just as surprised loading a more recent version fixed it 😅
