### ISSUE TITLE
`local -a` array combined with '#' strings breaks syntax highlighting

### ISSUE THREAD

**Issue by mattmc3** [jeff-hykin/better-shell-syntax#43]
## The code with a problem is:

This one is a weird one. A multi-line array declared as `local -a` with a '#' in the string breaks syntax highlighting.

Simple case that works correctly:
```zsh
function foo {
  local -a arr=('#')
  echo blah
}
```

Simple case that breaks:
```zsh
function bar {
  local -a arr=(
    '#'
  )
  echo blah
}
```

## It looks like:

See `baz`

<img width="295" alt="Screenshot 2023-02-09 at 11 25 09 AM" src="https://user-images.githubusercontent.com/978625/217874903-c14cb8f5-9df7-4368-abb1-860d3ed23b22.png">

## It should look like:

See `foo` or `bar` above.

**Comment by jeff-hykin** [comment]
Should now be fixed (I think a couple of versions ago, but working on `v1.4.3`)
