### ISSUE TITLE
Tab characters are not treated the same as spaces for tailing comments

### ISSUE THREAD

**Issue by mattmc3** [jeff-hykin/better-shell-syntax#44]
## The code with a problem is:
```zsh
#!/usr/bin/env zsh

function foo {
  echo "foo: $1"
}

foo bar  # trailing comments
foo baz		# tab trailing comments
```

## It looks like:
<img width="384" alt="Screenshot 2023-02-12 at 10 51 12 AM" src="https://user-images.githubusercontent.com/978625/218321571-bfaf4705-727b-4b86-9697-051460779650.png">

**Comment by jeff-hykin** [comment]
should now be fixed on v1.4.4
