### ISSUE TITLE
String ending single quote is missing a string scope

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-shell-syntax#47]
## The code with a problem is:
```shell
#!/usr/bin/env bash

declare -A juices=(
    ['apple']='Apple Juice'
    ['orange']='Orange Juice'
)

# This is a comment
echo "${juices['apple']}"
```

## It looks like:
![image](https://user-images.githubusercontent.com/38270282/221226264-53cffad0-d882-4096-a720-f0e9378166f0.png)

## It should look like:
The final quote on the line should still have the `string.quoted.single` scope.

**Comment by jeff-hykin** [comment]
alright should be fixed.

And @alexr00 idk if I mentioned this, but just encase you find it useful I couple weeks ago I published the original grammar as v0.0.1. So, if for some reason someone wants to go back, they can go all the way back to the original.
