### ISSUE TITLE
Inconsistency in detecting unquoted args within case statements according to whether or not a command is negated.

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-shell-syntax#51]
## The code with a problem is:
```shell
case "${1}" in
    0)  ls -la
        ;;
    1)  ! ls -la
```

## It looks like:
![image](https://user-images.githubusercontent.com/38270282/223683955-99d8254f-70b6-42a9-a559-287e5adb0422.png)

## It should look like:
I would expect `-la` to have the same scopes in both places it's used.

Originall from @frypf in https://github.com/microsoft/vscode/issues/176190#issuecomment-1459706171

**Comment by jeff-hykin** [comment]
duplicate of  #41 (recently renamed to be more clear)
