### ISSUE TITLE
String scope leaks out some lines

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-shell-syntax#53]
## The code with a problem is:
```shellscript
declare -A fileKeyFileMap=(["${VAR1}"]="${VAL1}" ["${VAR2}"]="${VAL2}")

logexit # log exit function
```

## It looks like:
![image](https://user-images.githubusercontent.com/38270282/224721765-a986d476-312f-4043-b4a8-98cd596aebb0.png)

## It should look like:
The `string.quoted.double` should not be on line 3. I pulled version `1.4.5` to make sure that this hasn't already been fixed.

Originally from @cipherdmg in https://github.com/microsoft/vscode/issues/173216#issuecomment-1465179486

**Comment by jeff-hykin** [comment]
temp fix `v1.5.1`. The full feature request of [] pattern-matching is still not handled, but should only localized miscoloring
