### ISSUE TITLE
Array Syntax Has Inconsistent Highlighting

### ISSUE THREAD

**Issue by akpircher** [jeff-hykin/better-shell-syntax#55]
## The code with a problem is:
https://gist.github.com/akpircher/1e30212e219104e1de6d5b38a9a9bc0e

## What it looks like:
**VSCode Theme**: Default Dark+

1. **Handling Array Parameters**
I don't know if this is a bug or intentional, it just seems inconsistent
![array-handling](https://user-images.githubusercontent.com/8506086/225793621-e546ecdb-f6eb-414d-b624-792a2896f1e3.png)

2. **Highlight inconsistencies with inline vs multi-line case statements**

    | demo | comparison |
    | --- | ---- | 
    | ![case-weirdness-demo] | ![case-weirdness-comp] |

3. **Other inline detection weirdness**

    | demo | comparison |
    | ---- | ---------- |
    | ![inline-weirdness-demo] | ![inline-weirdness-comp] |

## It should look like:
- **1. Array parameters**: I don't have strong feelings about what it _should_ look like, but having 
  the fallback match the same color used for "other" or "generic string" syntax makes it look
  broken. If a theme doesn't implement a specific highlight, then it should probably match the
  rest of the variable color, but maybe that's just because it's what I'm used to?
  - side note: it's very cool that I _could_ make it a different color, I might later.
- **2 - 3** Ideally, the syntax highlighting in the `demo` screen shots should match the syntax 
  highlighting in the `comparison` screen shots.

[case-weirdness-demo]: https://user-images.githubusercontent.com/8506086/225794450-25857e13-baa6-4c39-b1ce-4ee8c03e0da6.png
[case-weirdness-comp]: https://user-images.githubusercontent.com/8506086/225794533-829fff06-2942-4c25-ab85-b23c887c8d65.png
[inline-weirdness-comp]: https://user-images.githubusercontent.com/8506086/225794740-7706e906-933f-4f0e-927f-4301c3c29144.png
[inline-weirdness-demo]: https://user-images.githubusercontent.com/8506086/225794757-bf82a23d-324e-46c3-8682-9da7ea6277a0.png

_Originally posted by @akpircher in https://github.com/microsoft/vscode/issues/176190#issuecomment-1473026366_

**Comment by akpircher** [comment]
There's another case-statement situation that has actual broken syntax with inline case statements and arrays:

| demo | comparison |
| -- | -- |
| ![arrays-in-case-broken] | ![arrays-in-case-not-broken] |

I noticed #41, which is specific to the case-statements, after migrating the issue over. I'm not sure where you want to track this array-breaking issue, though.

[arrays-in-case-broken]: https://user-images.githubusercontent.com/8506086/226077812-4be691fa-7ccb-476d-9808-e4594f540869.png
[arrays-in-case-not-broken]: https://user-images.githubusercontent.com/8506086/226077815-92e7f307-50f8-44fa-a327-d307ddb9ff28.png

**Comment by jeff-hykin** [comment]
Right now there's basically no array support, so the behavior is just to minimized breakages caused by []'s

I don't know much about the POSIX, Bash, and Zsh specifications of arrays. So if you're feeling generous, linking specifications or explaining the syntax would help speed up the implementation of highlighting array syntax.

**Comment by jeff-hykin** [comment]
I'm going to focus this issue to array syntax, I opened up a new one for the local keyword, and I'll use #41 to focus on case-statement issues.

**Comment by akpircher** [comment]
I'm more than happy to provide documentation for POSIX/bash. I have gotten quite familiar with navigating their specification and info pages. This is taking a minute, because I'd like to compile some helpful information (re: summarize the important details hidden in paragraphs), but you can expect something today.

I hear zsh is similar, but I haven't actually used it.

**Comment by akpircher** [comment]
## Quick Reference Guides
- [Bash scripting cheatsheet]: Super quick reference of available syntax and tests
- [Bash Hackers Wiki]: A more descriptive cheat sheet

## GNU Bash Documentation
- [Shell Parameter Expansion] has a complete list of all parameter expansions syntax with examples, which also apply to arrays. Scroll past the paragraphs.
  - **Detail hidden in paragraphs**: the first 4 examples (the parameter value test expansions, like `:-`) do NOT need the colon. The colon means "unset or empty" and without the colon the tests just means "unset"
  - **Documented ...somewhere?**: when using a (numeric) variable for the key of an indexed array, or a variable for the offset/length, you can reference the variable without the expansion identifier (`$`)
      - This applies to any situation where shell arithmetic can be performed

- [Shell Arithmetic] has a complete list of shell arithmetic operators
  - **Detail hidden in first paragraph**: the syntax is valid in the following:
    - **`let`** `expression[s]`
    - **`declare -i`** `expression[s]`
    - **`local -i`** `expression[s]`
    - **`((`**`expression[s]`**`))`** and **`$((`**`expression[s]`**`))`**
  - **Detail hidden later**: bash supports the base syntax of
    `base#value`, which looks like it's covered.

### Builtin references pages
- [Bash Builtins] can direct you to where to find builtin commands/functions.
  - Pages you may care about are:
    - [Bourne Shell Builtins] and [Bash Builtin Commands]
    - The links in the 3rd paragraph
  - Ignore:
    - Modifying shell, it's a TOC for the `set` and `shopt` commands (not actually listed elsewhere)
    - "Special Builtins", describes behavior of previously listed builtins in POSIX mode


[Bash scripting cheatsheet]: https://devhints.io/bash
[Bash Hackers Wiki]: https://wiki.bash-hackers.org/
[Shell Parameter Expansion]: https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
[Shell Arithmetic]: https://www.gnu.org/software/bash/manual/html_node/Shell-Arithmetic.html
[Bash Builtins]: https://www.gnu.org/software/bash/manual/html_node/Shell-Builtin-Commands.html
[Bourne Shell Builtins]: https://www.gnu.org/software/bash/manual/html_node/Bourne-Shell-Builtins.html
[Bash Builtin Commands]: https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html

**Comment by jeff-hykin** [comment]
Alright I think these have been fixed (local, case and array) v1.8.5. I'll be honest I haven't yet read the builtins doc's so I can't be too certain. Free to test out the edgecases and open this back up if any are found.

Thanks again for linking the docs. My guess is there's still problems with `((` vs `$((` so I'm going to need to read the docs on those.

Parameter expansion is yet to be solved/highlighted, but there's another issue for it.
