### ISSUE TITLE
Variable name highlighting wrong within curly braces

### ISSUE THREAD

**Issue by bland328** [jeff-hykin/better-shell-syntax#57]
## The code with a problem is:
```
VAR1="$VAR2"	# correct
VAR1="${VAR2}"	# incorrect
```

## It looks like:
<img width="206" alt="Screenshot 2023-03-21 at 10 45 03 AM" src="https://user-images.githubusercontent.com/8441277/226674754-05699253-f15e-4ab5-92c2-17274427dd12.png">

## It should look like:
`${VAR2}` should be highlighted like `$VAR`.

**Comment by jeff-hykin** [comment]
This is what it looks like for me. Are you on the latest version?
<img width="381" alt="Screen Shot 2023-03-21 at 1 59 03 PM" src="https://user-images.githubusercontent.com/17692058/226713463-547fcd47-fb6c-4030-b4da-8252ca944414.png">
