### ISSUE TITLE
`continue` does not highlight unless outside of anything

### ISSUE THREAD

**Issue by 1480c1** [jeff-hykin/better-shell-syntax#58]
## The code with a problem is:
```bash
#!/usr/bin/bash

while :; do
    continue
    break
done
for i in $(seq 1 10); do
    continue
    break
done
until :; do
    continue
    break
done
if :; then
    continue
    break
fi
continue

```

## It looks like:
![image](https://user-images.githubusercontent.com/8345542/227754981-76d38bae-ec12-464a-8b90-0f17481a1c33.png)
Applies to all current VS Code Themes as far as I can tell in both general and insiders and with the plugin installed at version v1.5.2

## It should look like:
`continue` should have same color as `break`, especially inside loops

**Comment by jeff-hykin** [comment]
I'm not sure when this was fixed but it now seems to be fixed
