### ISSUE TITLE
# parsed as comment in zsh parenthesized qualifiers and flags

### ISSUE THREAD

**Issue by texastoland** [jeff-hykin/better-shell-syntax#6]
I found a zshism that doesn't highlight correctly in any grammar:

```zsh
#        (   )    zsh glob qualifiers
#         #q      glob expansion inside conditional expressions
#           N     null glob for no error if no matches
#                 then/fi not required in zsh
if [[ ! *(#qN) ]] echo nothing to see here
```

As a general rule zsh can place qualifiers in parentheses at the end of a glob or flags at the beginning of a glob or parameter expansion including the `#` character.

**Comment by jeff-hykin** [comment]
👍 thanks for reporting this I'm sure that really recks the code when it fails.

We might have to make a separate repo for zsh since, if this would fail in bash or others it would be nice to see that failure (ex: when converting a zsh script to bash) but it's good to report it here for now since this is a generic shell syntax.

**Comment by texastoland** [comment]
It isn't correct in Bash either:

```bash
      # ⌄       not a comment
echo *\(#qN\) # now a comment
# > *(#qN)
echo 'echo *\(#qN\)' > test.sh
source test.sh
# > *(#qN)
```

In general I don't think you can comment inside brackets. Here's a summary of zsh's syntactic differences I'm aware of:

1. brace-less array indexing like `$@[2,-1]`
1. nested parameter expansions like `${${(%):-%x}:P:h}`
1. parameter expansion flags and modifiers like above
1. extended glob operators like `*.(z,|)sh`
1. glob flags and qualifiers like `*(#qN)`
1. one-liner or brace-wrapped syntax for all keyword statements like `if`/`fi`

It would be a pain to parse in `shellcheck` or even `shfmt` but highlighting should take minimal additional effort.

**Comment by jeff-hykin** [comment]
Should be fixed as of today!
