### ISSUE TITLE
`declare` highlighting wrong

### ISSUE THREAD

**Issue by bland328** [jeff-hykin/better-shell-syntax#60]
## The code with a problem is:
```
#!/bin/bash
declare -A assoc_array
```

## It looks like:
<img width="166" alt="Screenshot 2023-03-29 at 12 31 26 PM" src="https://user-images.githubusercontent.com/8441277/228623068-ef794e1a-1c20-4312-90aa-5662ce3d85aa.png">

## It should look like:
`-A assoc_array` should not be highlighted

**Comment by jeff-hykin** [comment]
should be fixed now in 1.7.0
