### ISSUE TITLE
Autogenerated `shell.tmLanguage.json` file references non-existing `#statement_context` rule

### ISSUE THREAD

**Issue by sebthom** [jeff-hykin/better-shell-syntax#71]
See:
https://github.com/jeff-hykin/better-shell-syntax/blob/7220287a2e40d5909f346ebdc913a67c39f1927c/autogenerated/shell.tmLanguage.json#L1463-L1465

I guess this is supposed to be `"#normal_statement_context"`

**Comment by jeff-hykin** [comment]
thanks 👍
