### ISSUE TITLE
Syntax highlighting issue with "case" statement inside command substitution

### ISSUE THREAD

**Issue by friendly-bits** [jeff-hykin/better-shell-syntax#72]
## The code with a problem is:
```
#!/bin/sh

# The following line is valid shell code but everything after it is highlighted as a quote
test="$( case a in b ) printf '%s ' c; esac )"

# for example, this comment is highlighted as a quote
```

## It looks like:
![image](https://github.com/jeff-hykin/better-shell-syntax/assets/134004289/92dcc101-802c-4742-ad70-2c67e26a0a4c)

## It should look like:
Should not highlight everything after it as a quote.

**Comment by jeff-hykin** [comment]
redid the whole case syntax matching system, so this should be fixed in 1.7.0
