### ISSUE TITLE
Support for Fish functions

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-shell-syntax#78]
## The code with a problem is:
```fish
alias gswr='git switch -r'
alias gsws='git switch -s'

function sim
    if test $argv[1] = '--help'
        npm run p -- --help
    else
        make ls; and npm run p -- $argv
    end
end

set -x PATH /Users/ulugbekna/.dotnet $PATH
```

## It looks like:

![Image](https://github.com/jeff-hykin/better-shell-syntax/assets/38270282/c6a0a3e4-4570-4fbd-be86-83ed43cac5f2)

## It should look like:
The `meta.function.shell` scope continues past both of the `end`s, and at least one of those should cause it to exit. 

@jeff-hykin., Do you consider Fish to be supported by Better Shell Syntax? The syntax of Fish is different enough that I'm unsure what the expectation is! We added .fish to the list of file extensions about a year and a half ago, but that might have been incorrect. 

Originally from @ulugbekna in https://github.com/microsoft/vscode/issues/206952.

**Comment by jeff-hykin** [comment]
My official position is; as long as POSIX shell code is parsed correctly, then extra stuff can be added on. While bash/zsh are not POSIX, I think effectly all of their syntax is. 

Fish is very not POSIX, but it might still be possible to support the syntax. I'm not sure.

This particular case I think can be supported, but in the future a fork might be needed to support fish.

**Comment by jeff-hykin** [comment]
This particular case is fixed. Maybe later I'll open up an issue that covers all shell-syntax-conflicts
