### ISSUE TITLE
IF statement with basic math operations breaks syntax highlighting.

### ISSUE THREAD

**Issue by prplwtf** [jeff-hykin/better-shell-syntax#82]
## The code with a problem is:
```sh
if [[ ( $2 == "-i" ) || ( $2 == "-install" ) || ( $2 == "-add" ) ]]; then VCMD="y"
  if [[ $(( $# - 2 )) != 1 ]]; then PRINT FATAL "Expected 1 argument but got $(( $# - 2 )).";exit 2;fi
  # [..]
fi
```
https://github.com/BlueprintFramework/main/blob/da8b8001c4414c56fca9fcee46cb78dd2c36b41f/blueprint.sh#L323

## It looks like:
![image](https://github.com/jeff-hykin/better-shell-syntax/assets/103201875/1deb7c86-ca27-40dc-a9a0-7cfe57fd6ed7)
All commands below this IF statement have incorrect syntax highlighting.

## It should look like:
![image](https://github.com/jeff-hykin/better-shell-syntax/assets/103201875/90787e7a-42ed-4ce5-8a36-5af623e32b82)
Screenshot without the "Better Shell Syntax" VSCode extension enabled.

**Comment by jeff-hykin** [comment]
Alright should be sorta fixed now. Some of the math operators won't be highlighted, but I'm afraid there's not much that can be done about it.

```sh
check="$((xcode-\select --install) 2>&1)"
```

This ^ is valid but isn't arithmetic. And the parsing engine isn't smart enough to be able to "look ahead" and see if something ends with "))" or ends with ") 2>&1 )". We have to guess at the begining whether its arithmetic or not.

I might be able to add a hack in the future to improve the situation a bit, but for now v1.8.0 fixes the cascading breakage by assuming non-arithmetic.

**Comment by prplwtf** [comment]
Aright, thanks for fixing it.
